### ISSUE TITLE
Gulp/Ruby Error! Gem cmd is not installed.

### ISSUE THREAD

**Issue by MetaVisual** [planetoftheweb/sassEssentials#10]
I have poured at least 8 hours into troubleshooting with no avail to get Gulp to work properly. I am taking a course on sass and have downloaded its repository. Also, installed git bash, ruby, sass, and gulp. I have attached images that show my errors, versions of all in git, and my environmental variables paths in Windows 7.

When running gulp, I get error: 
" [22:32:30] Finished 'webserver' after 15 ms
Error! Gem cmd is not installed."

When doing a search it stated that my path in environmental variables needs to be directed to the ruby folder, which it is. 

Also, when I save the .scss file in Atom, I get the other error:
" 'node-sass' is not recognized as an internal or external command,
operable program or batch file."

I have uninstalled/reinstalled ruby 3 times and get the same error. Not sure what to do... Any help would be great. Thanks so much!
![errorinbashgulp](https://cloud.githubusercontent.com/assets/17764585/22376441/f2301764-e47b-11e6-9c1a-f02adcab9e42.jpg)
![errorinatomonsave](https://cloud.githubusercontent.com/assets/17764585/22376444/f6059b70-e47b-11e6-8aa7-486bc6f977c6.jpg)
![versions](https://cloud.githubusercontent.com/assets/17764585/22376451/fb76bb3e-e47b-11e6-935e-8f28bc721720.jpg)
![environmentalvariables](https://cloud.githubusercontent.com/assets/17764585/22376459/ff07a330-e47b-11e6-8961-d70a6695efab.jpg)
![rubyfolder](https://cloud.githubusercontent.com/assets/17764585/22376460/00b630a2-e47c-11e6-8b97-808af38ebf81.jpg)

**Comment by planetoftheweb** [comment]
Ruby installation issues are notoriously hard to debug. Did you try gem update before you did anything else.

**Comment by MetaVisual** [comment]
I did try to update sass gem by "gem update sass " command. The prompt returns "Nothing to update". 

I am unsure, but, think I have a Environmental Variables PATH issue. I pointed it to the Ruby folder (below), but no luck.

I attached two screenshots of my $PATH and users folder. Typing $PATH returns "bash: /c/Users/Chris/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/Chris/bin:x64/bin:/c/Users/Chris/AppData/Local/atom/bin:/c/Users/Chris/AppData/Roaming/npm:/c/Program: **No such file or directory**

**My current User and System Variables are**: C:\Ruby23-x64\bin;C:\Users\Chris\AppData\Local\atom\bin;C:\Users\Chris\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Ruby23-x64\lib\ruby\2.3.0\rubygems;C:\Users\Chris\path;C:\Users\Chris\.gem;C:\Users\Chris\rubygems;

Thank you for your reply and help!

Chris

![pathupdate](https://cloud.githubusercontent.com/assets/17764585/22451638/324036e4-e73e-11e6-9bde-67dc536c837a.jpg)
![userfolder](https://cloud.githubusercontent.com/assets/17764585/22451637/323fcbf0-e73e-11e6-83e9-2a42da708a32.jpg)
