### ISSUE TITLE
cloning the repository

### ISSUE THREAD

**Issue by MicKeyPhoenix77** [planetoftheweb/sassEssentials#17]
Hi, I'm a Lynda.com premium user. My issue is when I'm using the git clone and the URL, it only downloads 1 file. It only contains the same things as the master. It doesn't download the entire group of files for every chapter and each corresponding beginning and ending versions.

Issue: Cloning into 'sassEssentials'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 488 (delta 0), reused 0 (delta 0), pack-reused 487
Receiving objects: 100% (488/488), 1.14 MiB | 574.00 KiB/s, done.
Resolving deltas: 100% (180/180), done.

Other than this, the way you present the information is amazing. 

Thanks and God Bless.

Respectfully,

MicKey_Phoenix77

**Comment by planetoftheweb** [comment]
Hey there Mickey...When you clone a repo, it will always only clone only the master branch. You can get to the other branches, but they're sort of hidden.

If you want to download all of the branches issue these commands:

```
mkdir NAME
cd NAME
git clone --bare CLONEURL .git (make sure you add extra .git)
git config --bool core.bare false
git reset --hard
Run npm install to install the project dependencies
```

I created a course that shows you how to do this and gets you a better start with Github called Learning Git and Github. Check it out here: https://www.linkedin.com/learning/learning-git-and-github?u=104
