### ISSUE TITLE
This course is broken

### ISSUE THREAD

**Issue by KostaHS** [planetoftheweb/sassEssentials#25]
You might want to be clear in your course on the Gulp installation - you don't even go over it. And when I try to do it I get a 1001 errors:

https://share.getcloudapp.com/7Ku0vOGg

Well now I can't follow along. So frustrating.

**Comment by KostaHS** [comment]
Ok I figured it out :) - I don't now why you wouldn't go through installing Gulp in the course but anyway it's done.

**Comment by KostaHS** [comment]
Also how am I supposed to follow along when checking out a chapter branch completely breaks the gulp compile function??

**Comment by planetoftheweb** [comment]
Hmm. The descriptions on these issues aren't very clear. Gulp shouldn't break compile functions, but I'm not sure what you mean by compile functions. It always helps to do the npm install on the master branch, which is usually the final state of the project. Unfortunately, projects like Gulp often update and give you a ton of warnings. Even when I install things in recent projects, I get the warnings that some module is broken, which is what you might be seeing.

The installer should be giving you a notice that you can try an npm update, but even then that doesn't always fix modules.
