### ISSUE TITLE
ANSWER ME

### ISSUE THREAD

**Issue by KostaHS** [planetoftheweb/sassEssentials#26]
Can you f*cking answer me instead of just closing the issues??? Firstly - you need to add this to your course: 

https://timonweb.com/posts/how-to-fix-referenceerror-primordials-is-not-defined-error/

Your instructions are out of date - just getting everything working is a big nightmare and I don't get any responses from you here. Whatever obviously you don't support your course anymore - it's a f*cking nightmare you should say it's out of date so I can go somewhere else.

**Comment by KostaHS** [comment]
Even after I did that the HTML compiles but not the Saas - F*CK YOUR COURSE I"M GOING TO LODGE A COMPLAINT WITH LYNDA TO HAVE IT SHUT DOWN SO PEOPLE DON"T HAVE TO GO THROUGH THIS SH*T

**Comment by planetoftheweb** [comment]
Feel free to file a complaint. There's a feedback button on every page.

Having said that, I think that you probably need to learn how to file issues and what they're for. Issues that mention things like 1001 errors are not actionable. You need to calmly describe the problem, what you did and also add supporting information. (Here's the steps I tried, here's the error I received from the terminal, here's a screenshot of how it looks, etc.). Your descriptions aren't something that I can work with. I personally test every course, we have a team of people that also test every course. The course has already been watched by thousands of people and if something has cropped up which makes it out of date, I too would like to know how to correct it, but I can't do it if your issues are unclear or full of non-relevant information.

These posts are public, permanent records of your activity on Github. It's best to be civil and polite when asking for help. Personally, I understand the impolite language, I've been there before. I understand how frustrating it is when something isn't working, but posting things like this appear on your profile when potential employers are looking at your record of contribution. It would help to be polite when trying to work through a problem. Also, being able to give detailed issue descriptions is a core developer skill.

Don't let closing issues upset you. At some point you mentioned that you had figured it out and issues without proper documentation are not actionable. I can't do much with "I tried it (You tried what? What did you type, where? What steps did you follow?) and it doesn't work (What does the terminal say? Was it 1001 warnings or errors? What where the errors). It might help to read something like this: https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f

If things are bothering you so much, please take a break and come back and try later. Writing caustic comments on the weekends when I'm less active and expecting immediate responses isn't realistic. I'll be happy to try to help you figure things out if you want to continue in a polite and respectable fashion.

**Comment by KostaHS** [comment]
Hey mate, sorry about that. I did get it working in the end - I had someone install nvm and we switched to the correct version.

**Comment by planetoftheweb** [comment]
Ahh. Nvm so you can install multiple versions of node. That makes more sense. Thanks for leaving the solution so others can find it.
